__task 1__

In [1]:
import numpy as np

In [2]:
import numpy as np
np.random.seed(10)
raw = np.random.randint(1,10, (10,10))



In [3]:
def summa(arr):
    dop = np.eye(arr.shape[0])
    diag = arr*dop
    diag = diag[(diag%2==0)&(diag>0)]
    if np.sum(diag)==np.nan:
        return 0
    else:    
        return np.sum(diag)

In [4]:
summa(raw)

24.0

__task 2__

In [5]:
raw

array([[5, 1, 2, 1, 2, 9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9, 2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2, 5, 3, 7, 8, 9],
       [9, 3, 1, 7, 8, 9, 2, 8, 2, 5],
       [1, 9, 6, 5, 8, 9, 9, 3, 7, 3],
       [9, 9, 7, 7, 6, 7, 1, 1, 7, 2],
       [9, 2, 3, 9, 6, 1, 3, 8, 4, 1],
       [5, 3, 1, 4, 4, 2, 3, 6, 1, 2],
       [1, 2, 1, 3, 2, 2, 1, 1, 6, 1],
       [5, 7, 7, 1, 3, 4, 4, 3, 7, 1]])

In [6]:
razmer = raw.shape
tmp = raw.ravel()
tmp[np.argmax(raw)] = 1000
tmp = tmp.reshape(razmer)
tmp

array([[   5,    1,    2,    1,    2, 1000,    1,    9,    7,    5],
       [   4,    1,    5,    7,    9,    2,    9,    5,    2,    4],
       [   7,    6,    4,    7,    2,    5,    3,    7,    8,    9],
       [   9,    3,    1,    7,    8,    9,    2,    8,    2,    5],
       [   1,    9,    6,    5,    8,    9,    9,    3,    7,    3],
       [   9,    9,    7,    7,    6,    7,    1,    1,    7,    2],
       [   9,    2,    3,    9,    6,    1,    3,    8,    4,    1],
       [   5,    3,    1,    4,    4,    2,    3,    6,    1,    2],
       [   1,    2,    1,    3,    2,    2,    1,    1,    6,    1],
       [   5,    7,    7,    1,    3,    4,    4,    3,    7,    1]])

In [7]:
tmp[tmp==np.min(tmp)] = 0
tmp

array([[   5,    0,    2,    0,    2, 1000,    0,    9,    7,    5],
       [   4,    0,    5,    7,    9,    2,    9,    5,    2,    4],
       [   7,    6,    4,    7,    2,    5,    3,    7,    8,    9],
       [   9,    3,    0,    7,    8,    9,    2,    8,    2,    5],
       [   0,    9,    6,    5,    8,    9,    9,    3,    7,    3],
       [   9,    9,    7,    7,    6,    7,    0,    0,    7,    2],
       [   9,    2,    3,    9,    6,    0,    3,    8,    4,    0],
       [   5,    3,    0,    4,    4,    2,    3,    6,    0,    2],
       [   0,    2,    0,    3,    2,    2,    0,    0,    6,    0],
       [   5,    7,    7,    0,    3,    4,    4,    3,    7,    0]])